### ISSUE TITLE
Color format in `item` nodes

### ISSUE THREAD

**Issue by jrappen** [dracula/ulysses#2]
Greetings @nesl247, @briantkatch, @zenorocha,

could you provide any information about the color format used in Ulysses themes for `item` nodes?

**Comment by briantkatch** [comment]
This is a copy paste from when I emailed their support team about the issue. This is from 2015 so not sure if it is still up to date.  

Hi Brian,  

You shouldn’t necessarily need a light version of the theme. If you don’t include the color palette for light, the light colors will be empty (as far as I can see). Alternatively, you could just use the same colors are in dark mode. The color elements in <palette> are as follows:  
- the foreground color (i.e. the text color when no tag is applied)  
- the background color  
- 11 accent colors. These don’t need to have a specific order.  

All hex colors are always in RGBA, i.e. the least significant bits represent the alpha value.  

You can just leave the <item> elements with scope/definition as they are, they are just used internally when programmatically setting up themes.  

Best,  
Götz  

> On 28 Oct 2015, at 00:16, Brian Tkatch <brian@defectivebit.com> wrote:  
>  
> Thanks for the help. Do I need to include a light version of my theme? Also, inside each <palette> elements it seems that the <color> elements are in a particular order - can you give me a reference as to the order to use? Also, can you explain the purpose of the <item> elements with the scope and definition attributes? I’m working with a copy of the Yosemite theme, if it’s relevant.  
>  
> Thanks, -Brian  
>  
>  
>  
> On October 27, 2015 at 01:54:04, The Soulmen Support (support@the-soulmen.com) wrote:  
> > Hi Brian,  
> >  
> > The .ultheme format is not publicly documented, because the format is still subject to change. It is basically a zip file containing small and large preview images (for both light and dark mode) and a file called “Theme.xml”, which contains the color information.  
> >  
> > You should be able to leave out the PNG files and just store the Theme.xml in the zip file, this should work.  
> >  
> > Hope this helps,  
> > Götz

**Comment by jrappen** [comment]
Thanks for the input, that corresponds to the observed behavior. Still unexpected to include the irrelevant item nodes, though.
